
while True:
    playgame = input("Do you want to play? (yes/no)\n").lower()
    if playgame == "yes":
        print("You wake up in a dark room....")
        answer = input("do you search the room or leave immediately? (leave/search)\n").lower()# todo finish the leave path
        if answer == "leave":
            print("you are in a hallway, there is noise downsome stairs or another closed door")
        elif answer == "search":
            print("you find a small knife and some money in the room...")
            print("There is a lot of noise being made downstairs...")
            print("you hear someone running upstairs!...")
            answer = input("hide? or get ready to fight? (hide/fight)\n").lower()
            if answer == "hide":
                print("You scurry behind a cupboard in the corner...")
                print("A frantic man crashes through the door..")
                print('"Fuck!... he was meant to be here, I shouldn\'t have risked coming here to get him"...')
                answer = input("You have a slight feeling of recognition about this man but are unsure whether to reveal yourself...(reveal/hide)\n").lower()
                if answer == "reveal":
                    print('"Hello? you say nervously"...')
                    print('"There you are! were you hiding?..."')
                    print('"never mind that we need to"...')
                    print("He is cut of as a man slams into him...")
                    print("He screams as a knife is raised and slashed across his body multiple times, the wounds look deep...")
                    print("No choice here... YOU RUN!!!")
                    print("You run out the door leaving the attacker behind, there is another in the hall, shocked by your appearance...")
                    print("He grabs for you, but adrenaline means you are quick. You dodge under his arm and sprint down the stairs...")
                    print("downstairs you see a thick wooden door, it looks like it leads outside...")
                    print("You dash for it, throwing it open and sprint out into the dark nights streets...")
                    print("With no knowledge of where you are you have to run aimlessly...")
                    print("Who knows where you will end up...")
                    print("Thank you for playing")
                    print("Let me know what you think")
                elif answer == "hide":
                    print("You stay in the corner as two men rush into the room...")
                    print("The man on his own tries to fight off these men with a simple cudgle...")
                    print("During the struggle, you see a knife plunge into the neck of the man and he topples to the floor...")
                    print("The two men catch their breath, and eyes begin to wander around the room...")
                    print("...They see you!...")
                    print('The one with the bloodied knife steps toward you as he mutters... "been nothing but trouble these two..."')
                    print("A glimmer of light off the steel blade flashes rapidly across your eyes...")
                    print("A pain unlike any you have known erupts from you chest...")
                    print("It fades rapidly as do you... into the darkness")
                    print("Game over thanks for playing")
            elif answer == "fight":
                print("You tense, readying your weapon as you sense someone run up to the rooms door...")
                print("The door swings open!...")
                print('"Aww thank fuck you\'re alright!", A broad shouldered man gushes in relief...')
                print("he glances at your poised knife...")
                print(''"Good we are about to have company. Don't know if I could have handled them on my own"'')
                print("Two men speed into the room with fury on their faces")
                answer = input("Do you attack aggressively? or hang back defensively? (attack/defend)\n").lower()
                if answer == "attack":
                    print("You lunge for the man in front of you, slashing wildly in frenzy...")
                    print("He stumbles backwards, sent off balance by your sudden lunge forwards...")
                    print("He trips on a stool by a desk, here is your opening!...")
                    print("You slash his forearm disarming him...")
                    print("In an attempt to immobilise him you cut into his right thigh, nothing deadly but it will hurt...")
                    print("Confident he is no longer a threat you spin around to check on your new companion...")
                    print("He seems to have won his bout as well, stunning his foe with a cudgel blow to the head...")
                    print('The foe, while sluggish, may come around soon,"Let\'s go!" you yell...')
                    print("You both make a dash for the door, falling in behind you follow this man out of the house, where, for a moment, you catch your breath.")
                    print('"Jesus what was that all about?" you say...')
                    print('You don\'t know?" You get in reply...')
                    print('"God I thought the boss would be pissed before, if you haven\'t got any answers for him, I don\'t know what we will do"...')
                    print('"Come on we should get gone quick, get you all caught up"...')
                    print("You both run off into the night...")
                    print("Thank you for playing")
                    print("Game over")
                elif answer == "defend":
                    print("The man pushes forwards at you, slashing erratically as he does...")
                    print("He shallowly cuts your upper arm but exposed himself in his frenzy...")
                    print("You smash your fist into his ribs, you hear a dull crack as your fist connects...")
                    print("shocked by your own strength in the moment you step back...")
                    print("Luckily, the man just holds his side struggling to cope with the pain of the blow...")
                    print("You seem to be safe from him for now, your cut will need treating soon however...")
                    print("You spin around to check on your new companion...")
                    print("He seems to have won his bout as well, stunning his foe with a cudgel blow to the head...")
                    print('The foe, while sluggish, may come around soon,"Let\'s go!" you yell...')
                    print("You both make a dash for the door, falling in behind you follow this man out of the house, where, for a moment, you catch your breath.")
                    print('"Jesus what was that all about?" you say...')
                    print('You don\'t know?" You get in reply...')
                    print('"God I thought the boss would be pissed before, if you haven\'t got any answers for him, I don\'t know what we will do"...')
                    print('"Come on we should get gone quick, get you all caught up"...')
                    print("You both run off into the night...")
                    print("Thank you for playing")
                    print("Game over")

        else:
            print("wrong input")
    else:
        print("Come back when you want to play")
        break